config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :books, only: [:index, :show, :create, :update, :destroy, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :update, :edit] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'home/about' => 'homes#about', as: 'about'
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    @book_comment = BookComment.new
  end

  def destroy
    @book_comment = BookComment.find(params[:id])
    @book = @book_comment.book
    @book_comment.destroy
    @book_comment = BookComment.new
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)

  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comments.html.erb
<% if book.user != current_user %>
  <%= form_with model: book_comment, url: book_book_comments_path(book), local: false do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: 'Comment here', class: "w-50 d-block" %>
    <%= f.submit 'Submit', class: "btn btn-success mt-3" %>
  <% end %>
<% end %>
<table class="table table-hover mt-3">
  <tbody>
    <% book.book_comments.each do |book_comment| %>
      <tr>
        <td><%= image_tag book_comment.user.get_profile_image(70,70) %></td>
        <td><%= link_to book_comment.user.name, user_path(book_comment.user) %></td>
        <td><%= book_comment.comment %></td>
        <td><%= book_comment.created_at.strftime('%y/%m/%d') %></td>
        <td>
        <% if book_comment.user == current_user %>
          <%= link_to 'Delete', book_book_comment_path(book.id, book_comment.id), method: :delete, class: "btn btn-outline-danger btn-sm", remote: true %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/book_comments/create.js.erb
$('#book_comments').html('<%= j(render "book_comments/comments", book: @book, book_comment: @book_comment) %>');
$('textarea[name="book_comment[comment]"]').val('');

app/views/book_comments/destroy.js.erb
$('#book_comments').html('<%= j(render "book_comments/comments", book: @book, book_comment: @book_comment) %>');