config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :books, only: [:index, :show, :create, :update, :destroy, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :update, :edit] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'home/about' => 'homes#about', as: 'about'
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:name]

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.page(params[:page])
    @user = current_user
    @book = Book.new
  end

  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated successfully'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page])
    @book = Book.new
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userinfo.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User Info</h2>
        <table>
          <thread>
                <tr>
                  <th><%= image_tag current_user.get_profile_image(100,100) %></th>
                </tr>
          </thread>
          <tbody>
            <tr>
              <th>name</th>
              <td><%= current_user.name %></td>
            </tr>
            <tr>
              <th>introduction</th>
              <td><%= current_user.introduction %></td>
            </tr>
          </tbody>
        </table>
        <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
          <i class="fa-solid fa-user-gear"></i>
        <% end %>
        <h2>New Book</h2>
        <%= form_with model: @book do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>
    </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <h2>User Info</h2>
      <%= render 'layouts/errormessage', object:@user %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <%= f.label :Name, "Name", class: "control-label" %>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control"  %>
        </div>
        <div class="form-group">
          <%= f.label :Image, "Image", class: "control-label" %>
          <div class="custom-file">
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :Introduction, "Introduction", class: "control-label" %>
          <%= f.text_area :introduction, rows: 2, id:"inputIntroduction", placeholder:"紹介", class: "form-control"  %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-3">
      <%= render 'layouts/user_info', user:current_user %>
      <%= render 'layouts/new_book', book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">image</th>
            <th scope="col">name</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <th scope="row"><%= image_tag user.get_profile_image(100,100) %></th>
              <td><%= user.name %></td>
              <td>followings: <%= user.followings.count %></td>
              <td>followers: <%= user.followers.count %></td>
              <td>
                <% if current_user != user %>
                  <% if current_user.following?(user) %>
                    <%= link_to "Following", user_relationships_path(user.id), method: :delete %>
                  <% else %>
                    <%= link_to "Follow", user_relationships_path(user.id), method: :post %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to 'Show', user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-3">
      <%= render 'layouts/errormessage', object:@book %>
      <%= render 'layouts/user_info', user:@user %>
      <%= render 'layouts/new_book', book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Title</th>
            <th scope="col">Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <div>
                  <%= link_to user_path(book.user) do %>
                    <%= image_tag book.user.get_profile_image(80,80) %>
                  <% end %>
                  </div>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td>コメント数: <%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= paginate @books %>
  </div>
</div>