config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :books, only: [:index, :show, :create, :update, :destroy, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :update, :edit] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'home/about' => 'homes#about', as: 'about'
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form mt-3">
    <%= form_with url: search_path, local: true, method: :get, class: "form-inline" do |f| %>
      <div class="form-group mr-2">
        <%= f.text_field :word, class: "form-control form-control-sm", placeholder: "Search word..." %>
      </div>
      <div class="form-group mr-2">
        <%= f.select :range, options_for_select([['User'], ['Book']]), {}, {class: 'form-control form-control-sm'} %>
      </div>
      <div class="form-group mr-2">
        <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]), {}, {class: 'form-control form-control-sm'} %>
      </div>
      <div class="form-group mr-2">
        <%= f.submit "Search", class: "btn btn-outline-primary btn-sm" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 justify-content-center mt-3">
      <h2>Results</h2>
      <table class="table table-hover">
        <% if @range == "User" %>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.get_profile_image(50,50) %></td>
                <td><%= user.name %></td>
                <td>Following: <%= user.followings.count %></td>
                <td>Followers: <%= user.followers.count %></td>
                <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
              </tr>
            <% end %>
          </tbody>
        <% else %>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= image_tag book.user.get_profile_image(50,50) %></td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>
                <td>Likes: <%= book.favorites.count %></td>
              </tr>
            <% end %>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>