config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :books, only: [:index, :show, :create, :update, :destroy, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :update, :edit] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'home/about' => 'homes#about', as: 'about'
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:name]

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: true
  validates :introduction, length: {maximum: 50}


  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]


  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    @book_comment = BookComment.new
  end

  def destroy
    @book_comment = BookComment.find(params[:id])
    @book = @book_comment.book
    @book_comment.destroy
    @book_comment = BookComment.new
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @book = Book.new
    @books = Book.page(params[:page])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'Book was successfully created'
      redirect_to book_path(@book)
    else
      @books = Book.all.page(params[:page])
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.'
      redirect_to @book
    else
      render :edit
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.page(params[:page])
    @user = current_user
    @book = Book.new
  end

  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated successfully'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page])
    @book = Book.new
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type.to_sym
    when :success
      "success"
    when :error
      "danger"
    when :alert
      "warning"
    when :notice
      "info"
    else
      flash_type.to_s
    end
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errormessage.html.erb
<% if object.present? && object.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <strong><%= object.errors.count %>件のエラーが発生しました</strong>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer container-fluid">
  <div class="row">
    <p class="mx-auto pt-4">CopyRight Infratop.inc</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Bookers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to user_path(current_user), class: "nav-link text-light" do %>
              <i class="fa-solid fa-home"></i> Home
            <% end %>
          <li class="nav-item">
            <%= link_to users_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-users"></i> Users
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-book-open"></i> Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
              <i class="fa-solid fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-home"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to about_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-link"></i> About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to user_session_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_new_book.html.erb
<h2 class="mt-3">New book</h2>
<%= render 'layouts/errormessage', object:@book %>
<%= form_with model: book, html: {class: 'form-horizontal'} do |f| %>
<div class="form-group">
  <h4 class="control-label">Title</h4>
  <%= f.text_field :title, placeholder: "Title here", class: "form-control" %>
</div>
<div class="form-group">
  <h4 class="control-label">Opinion</h4>
  <%= f.text_area :body, rows: 4, placeholder: "Opinion here", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.submit 'Create Book', class: "btn btn-outline-success" %>
</div>
<% end %>

app/views/layouts/_user_info.html.erb
<h2>User Info</h2>
<%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tbody>
      <tr>
        <th scope="row">name</th>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <th scope="row">introduction</th>
        <td><%= user.introduction %></td>
      </tr>
      <tr>
        <th scope="row">follows</th>
        <td><%= link_to user.followings.count, user_followings_path(user) %></td>
      </tr>
      <tr>
        <th scope="row">followers</th>
        <td><%= link_to user.followers.count, user_followers_path(user) %></td>
      </tr>
    </tbody>
  </table>
  <div>
    <% if current_user == user %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fa-solid fa-user-cog"></i>
      <% end %>
    <% else %>
      <% if current_user.following?(user) %>
        <%= link_to "Following", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-info" %>
      <% else %>
        <%= link_to "Follow", user_relationships_path(user.id), method: :post, class: "btn btn-outline-primary" %>
      <% end %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/e48857b0b3.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |key, message| %>
      <div class="alert alert-<%= bootstrap_class_for_flash(key) %>">
        <%= message %>
      </div>
    <% end %>
    <div class="d-flex">
      <div class="ml-auto">
        <%= render 'searches/search' %>
      </div>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>